# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './viewports/conflicts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0910909, y1:0.108, x2:1, y2:1, stop:0 rgba(15, 41, 46, 255), stop:1 rgba(26, 109, 117, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_conflicts_conflictslist = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_conflicts_conflictslist.setGeometry(QtCore.QRect(20, 70, 371, 461))
        self.listWidget_conflicts_conflictslist.setStyleSheet("font: 57 14pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.listWidget_conflicts_conflictslist.setObjectName("listWidget_conflicts_conflictslist")
        self.button_conflicts_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_conflicts_back.setGeometry(QtCore.QRect(20, 540, 171, 41))
        self.button_conflicts_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_conflicts_back.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_conflicts_back.setObjectName("button_conflicts_back")
        self.button_conflicts_newConflict = QtWidgets.QPushButton(self.centralwidget)
        self.button_conflicts_newConflict.setGeometry(QtCore.QRect(200, 540, 191, 41))
        self.button_conflicts_newConflict.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_conflicts_newConflict.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_conflicts_newConflict.setObjectName("button_conflicts_newConflict")
        self.dropdown_conflicts_newConflictArticleName = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown_conflicts_newConflictArticleName.setGeometry(QtCore.QRect(400, 100, 381, 31))
        self.dropdown_conflicts_newConflictArticleName.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dropdown_conflicts_newConflictArticleName.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"color: rgb(255, 255, 255);")
        self.dropdown_conflicts_newConflictArticleName.setObjectName("dropdown_conflicts_newConflictArticleName")
        self.button_conflicts_deleteConflict = QtWidgets.QPushButton(self.centralwidget)
        self.button_conflicts_deleteConflict.setGeometry(QtCore.QRect(420, 540, 181, 41))
        self.button_conflicts_deleteConflict.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_conflicts_deleteConflict.setStyleSheet("background-color: rgba(220, 100, 120, 150);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_conflicts_deleteConflict.setObjectName("button_conflicts_deleteConflict")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.input_conflicts_articleId = QtWidgets.QComboBox(self.centralwidget)
        self.input_conflicts_articleId.setGeometry(QtCore.QRect(20, 20, 371, 31))
        self.input_conflicts_articleId.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.input_conflicts_articleId.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"color: rgb(255, 255, 255);")
        self.input_conflicts_articleId.setObjectName("input_conflicts_articleId")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Konflikte / Regeln"))
        self.button_conflicts_back.setToolTip(_translate("MainWindow", "Esc"))
        self.button_conflicts_back.setText(_translate("MainWindow", "Zurück"))
        self.button_conflicts_back.setShortcut(_translate("MainWindow", "Esc"))
        self.button_conflicts_newConflict.setToolTip(_translate("MainWindow", "Strg + Enter"))
        self.button_conflicts_newConflict.setText(_translate("MainWindow", "Neuer Konflikt"))
        self.button_conflicts_newConflict.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.button_conflicts_deleteConflict.setToolTip(_translate("MainWindow", "Strg + Entf"))
        self.button_conflicts_deleteConflict.setText(_translate("MainWindow", "Löschen"))
        self.label_3.setText(_translate("MainWindow", "Inkompatibler Artikel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
