# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './viewports/customers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0910909, y1:0.108, x2:1, y2:1, stop:0 rgba(15, 41, 46, 255), stop:1 rgba(26, 109, 117, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_customer_showProject = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_showProject.setGeometry(QtCore.QRect(420, 410, 341, 41))
        self.button_customer_showProject.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_showProject.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_customer_showProject.setObjectName("button_customer_showProject")
        self.input_customer_search = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_search.setGeometry(QtCore.QRect(20, 20, 311, 33))
        self.input_customer_search.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_search.setObjectName("input_customer_search")
        self.listWidget_customer_search = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_customer_search.setGeometry(QtCore.QRect(20, 70, 371, 461))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0910909, 0.108, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(15, 41, 46))
        gradient.setColorAt(1.0, QtGui.QColor(26, 109, 117))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.listWidget_customer_search.setPalette(palette)
        self.listWidget_customer_search.setStyleSheet("font: 57 14pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.listWidget_customer_search.setObjectName("listWidget_customer_search")
        self.input_customer_customerId = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_customerId.setGeometry(QtCore.QRect(420, 20, 341, 33))
        self.input_customer_customerId.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_customerId.setObjectName("input_customer_customerId")
        self.input_customer_lastname = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_lastname.setGeometry(QtCore.QRect(420, 70, 341, 33))
        self.input_customer_lastname.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_lastname.setObjectName("input_customer_lastname")
        self.input_customer_firsname = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_firsname.setGeometry(QtCore.QRect(420, 110, 341, 33))
        self.input_customer_firsname.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_firsname.setObjectName("input_customer_firsname")
        self.input_customer_city = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_city.setGeometry(QtCore.QRect(570, 170, 191, 33))
        self.input_customer_city.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_city.setObjectName("input_customer_city")
        self.input_customer_zip = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_zip.setGeometry(QtCore.QRect(420, 170, 141, 33))
        self.input_customer_zip.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_zip.setObjectName("input_customer_zip")
        self.input_customer_street = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_street.setGeometry(QtCore.QRect(420, 210, 271, 33))
        self.input_customer_street.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_street.setObjectName("input_customer_street")
        self.input_customer_streetnumber = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_streetnumber.setGeometry(QtCore.QRect(700, 210, 61, 33))
        self.input_customer_streetnumber.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_streetnumber.setObjectName("input_customer_streetnumber")
        self.input_customer_mail = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_mail.setGeometry(QtCore.QRect(420, 270, 231, 33))
        self.input_customer_mail.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_mail.setObjectName("input_customer_mail")
        self.dateEdit_customer_birthday = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_customer_birthday.setGeometry(QtCore.QRect(659, 270, 101, 31))
        self.dateEdit_customer_birthday.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 50);")
        self.dateEdit_customer_birthday.setObjectName("dateEdit_customer_birthday")
        self.button_customer_showOrders = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_showOrders.setGeometry(QtCore.QRect(420, 460, 341, 41))
        self.button_customer_showOrders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_showOrders.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_customer_showOrders.setObjectName("button_customer_showOrders")
        self.input_customer_company = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customer_company.setGeometry(QtCore.QRect(570, 330, 191, 33))
        self.input_customer_company.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_customer_company.setObjectName("input_customer_company")
        self.checkBox_customer_isCompany = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_customer_isCompany.setGeometry(QtCore.QRect(420, 330, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Maven Pro Medium")
        font.setPointSize(16)
        self.checkBox_customer_isCompany.setFont(font)
        self.checkBox_customer_isCompany.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.checkBox_customer_isCompany.setObjectName("checkBox_customer_isCompany")
        self.button_customer_deleteCustomer = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_deleteCustomer.setGeometry(QtCore.QRect(420, 540, 211, 41))
        self.button_customer_deleteCustomer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_deleteCustomer.setStyleSheet("background-color: rgba(220, 100, 120, 150);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.button_customer_deleteCustomer.setObjectName("button_customer_deleteCustomer")
        self.button_customer_newCustomer = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_newCustomer.setGeometry(QtCore.QRect(190, 540, 201, 41))
        self.button_customer_newCustomer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_newCustomer.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_customer_newCustomer.setObjectName("button_customer_newCustomer")
        self.button_customer_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_back.setGeometry(QtCore.QRect(20, 540, 161, 41))
        self.button_customer_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_back.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_customer_back.setObjectName("button_customer_back")
        self.button_customer_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_clear.setGeometry(QtCore.QRect(640, 540, 121, 41))
        self.button_customer_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_clear.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_customer_clear.setObjectName("button_customer_clear")
        self.button_customer_searchGo = QtWidgets.QPushButton(self.centralwidget)
        self.button_customer_searchGo.setGeometry(QtCore.QRect(340, 20, 51, 33))
        self.button_customer_searchGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_customer_searchGo.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_customer_searchGo.setObjectName("button_customer_searchGo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kunden"))
        self.button_customer_showProject.setToolTip(_translate("MainWindow", "Strg + P"))
        self.button_customer_showProject.setText(_translate("MainWindow", "Zeige Projekte"))
        self.button_customer_showProject.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.input_customer_search.setPlaceholderText(_translate("MainWindow", "Suche .."))
        self.input_customer_customerId.setPlaceholderText(_translate("MainWindow", "Kundennummer .."))
        self.input_customer_lastname.setPlaceholderText(_translate("MainWindow", "Nachname .."))
        self.input_customer_firsname.setPlaceholderText(_translate("MainWindow", "Vorname .."))
        self.input_customer_city.setPlaceholderText(_translate("MainWindow", "Ort .."))
        self.input_customer_zip.setPlaceholderText(_translate("MainWindow", "PLZ .."))
        self.input_customer_street.setPlaceholderText(_translate("MainWindow", "Straße .."))
        self.input_customer_streetnumber.setPlaceholderText(_translate("MainWindow", "Nr.."))
        self.input_customer_mail.setPlaceholderText(_translate("MainWindow", "Email .."))
        self.button_customer_showOrders.setToolTip(_translate("MainWindow", "Strg + B"))
        self.button_customer_showOrders.setText(_translate("MainWindow", "Zeige Bestellungen"))
        self.button_customer_showOrders.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.input_customer_company.setPlaceholderText(_translate("MainWindow", "Firma .."))
        self.checkBox_customer_isCompany.setText(_translate("MainWindow", "ist Händler"))
        self.button_customer_deleteCustomer.setToolTip(_translate("MainWindow", "Strg + Entf"))
        self.button_customer_deleteCustomer.setText(_translate("MainWindow", "Kunde löschen"))
        self.button_customer_deleteCustomer.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.button_customer_newCustomer.setToolTip(_translate("MainWindow", "Strg + Enter"))
        self.button_customer_newCustomer.setText(_translate("MainWindow", "Neuer Kunde"))
        self.button_customer_newCustomer.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.button_customer_back.setToolTip(_translate("MainWindow", "Esc"))
        self.button_customer_back.setText(_translate("MainWindow", "Zurück"))
        self.button_customer_back.setShortcut(_translate("MainWindow", "Esc"))
        self.button_customer_clear.setToolTip(_translate("MainWindow", "Strg + Rück (<--)"))
        self.button_customer_clear.setText(_translate("MainWindow", "leeren"))
        self.button_customer_clear.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.button_customer_searchGo.setToolTip(_translate("MainWindow", "Enter"))
        self.button_customer_searchGo.setText(_translate("MainWindow", "Los"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
