# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './viewports/mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./gui\\bike.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0910909, y1:0.108, x2:1, y2:1, stop:0 rgba(15, 41, 46, 255), stop:1 rgba(26, 109, 117, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_menu_customer = QtWidgets.QPushButton(self.centralwidget)
        self.button_menu_customer.setGeometry(QtCore.QRect(170, 90, 211, 171))
        self.button_menu_customer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_menu_customer.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_menu_customer.setObjectName("button_menu_customer")
        self.button_menu_logout = QtWidgets.QPushButton(self.centralwidget)
        self.button_menu_logout.setGeometry(QtCore.QRect(613, 540, 181, 51))
        self.button_menu_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_menu_logout.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_menu_logout.setObjectName("button_menu_logout")
        self.button_menu_article = QtWidgets.QPushButton(self.centralwidget)
        self.button_menu_article.setGeometry(QtCore.QRect(400, 90, 211, 171))
        self.button_menu_article.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_menu_article.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_menu_article.setObjectName("button_menu_article")
        self.button_menu_order = QtWidgets.QPushButton(self.centralwidget)
        self.button_menu_order.setGeometry(QtCore.QRect(170, 280, 211, 171))
        self.button_menu_order.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_menu_order.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_menu_order.setObjectName("button_menu_order")
        self.button_menu_rules = QtWidgets.QPushButton(self.centralwidget)
        self.button_menu_rules.setGeometry(QtCore.QRect(400, 280, 211, 171))
        self.button_menu_rules.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_menu_rules.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_menu_rules.setObjectName("button_menu_rules")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zweirad Laden - Hauptmenü"))
        self.button_menu_customer.setToolTip(_translate("MainWindow", "K"))
        self.button_menu_customer.setText(_translate("MainWindow", "Kunden"))
        self.button_menu_customer.setShortcut(_translate("MainWindow", "K"))
        self.button_menu_logout.setToolTip(_translate("MainWindow", "Strg + L"))
        self.button_menu_logout.setText(_translate("MainWindow", "logout"))
        self.button_menu_logout.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.button_menu_article.setToolTip(_translate("MainWindow", "A"))
        self.button_menu_article.setText(_translate("MainWindow", "Artikel"))
        self.button_menu_article.setShortcut(_translate("MainWindow", "A"))
        self.button_menu_order.setToolTip(_translate("MainWindow", "B"))
        self.button_menu_order.setText(_translate("MainWindow", "Bestellungen"))
        self.button_menu_order.setShortcut(_translate("MainWindow", "B"))
        self.button_menu_rules.setToolTip(_translate("MainWindow", "R"))
        self.button_menu_rules.setText(_translate("MainWindow", "Regelwerk"))
        self.button_menu_rules.setShortcut(_translate("MainWindow", "R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
