# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './viewports/order_lineitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0910909, y1:0.108, x2:1, y2:1, stop:0 rgba(15, 41, 46, 255), stop:1 rgba(26, 109, 117, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_orderlineitem_lineitemlist = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_orderlineitem_lineitemlist.setGeometry(QtCore.QRect(20, 70, 371, 461))
        self.listWidget_orderlineitem_lineitemlist.setStyleSheet("font: 57 14pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.listWidget_orderlineitem_lineitemlist.setObjectName("listWidget_orderlineitem_lineitemlist")
        self.input_orderlineitem_orderId = QtWidgets.QLineEdit(self.centralwidget)
        self.input_orderlineitem_orderId.setGeometry(QtCore.QRect(20, 20, 311, 33))
        self.input_orderlineitem_orderId.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_orderlineitem_orderId.setObjectName("input_orderlineitem_orderId")
        self.input_orderlineitem_totapriceExVat = QtWidgets.QLineEdit(self.centralwidget)
        self.input_orderlineitem_totapriceExVat.setGeometry(QtCore.QRect(410, 235, 171, 33))
        self.input_orderlineitem_totapriceExVat.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_orderlineitem_totapriceExVat.setObjectName("input_orderlineitem_totapriceExVat")
        self.button_orderlineitem_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_orderlineitem_back.setGeometry(QtCore.QRect(20, 540, 171, 41))
        self.button_orderlineitem_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_orderlineitem_back.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_orderlineitem_back.setObjectName("button_orderlineitem_back")
        self.button_orderlineitem_newOrderlineitem = QtWidgets.QPushButton(self.centralwidget)
        self.button_orderlineitem_newOrderlineitem.setGeometry(QtCore.QRect(200, 540, 191, 41))
        self.button_orderlineitem_newOrderlineitem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_orderlineitem_newOrderlineitem.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_orderlineitem_newOrderlineitem.setObjectName("button_orderlineitem_newOrderlineitem")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 210, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 211, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.dropdown_orderlineitem_Article = QtWidgets.QComboBox(self.centralwidget)
        self.dropdown_orderlineitem_Article.setGeometry(QtCore.QRect(410, 70, 351, 31))
        self.dropdown_orderlineitem_Article.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"color: rgb(255, 255, 255);")
        self.dropdown_orderlineitem_Article.setObjectName("dropdown_orderlineitem_Article")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.input_orderlineitem_totapriceIclVat = QtWidgets.QLineEdit(self.centralwidget)
        self.input_orderlineitem_totapriceIclVat.setGeometry(QtCore.QRect(600, 235, 171, 33))
        self.input_orderlineitem_totapriceIclVat.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_orderlineitem_totapriceIclVat.setObjectName("input_orderlineitem_totapriceIclVat")
        self.button_orderlineitem_saveLine = QtWidgets.QPushButton(self.centralwidget)
        self.button_orderlineitem_saveLine.setGeometry(QtCore.QRect(650, 540, 131, 41))
        self.button_orderlineitem_saveLine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_orderlineitem_saveLine.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_orderlineitem_saveLine.setObjectName("button_orderlineitem_saveLine")
        self.button_orderlineitem_deleteLine = QtWidgets.QPushButton(self.centralwidget)
        self.button_orderlineitem_deleteLine.setGeometry(QtCore.QRect(420, 540, 111, 41))
        self.button_orderlineitem_deleteLine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_orderlineitem_deleteLine.setStyleSheet("background-color: rgba(220, 100, 120, 150);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_orderlineitem_deleteLine.setObjectName("button_orderlineitem_deleteLine")
        self.input_order_singleitem_priceExVat = QtWidgets.QLineEdit(self.centralwidget)
        self.input_order_singleitem_priceExVat.setGeometry(QtCore.QRect(410, 134, 171, 33))
        self.input_order_singleitem_priceExVat.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_order_singleitem_priceExVat.setText("")
        self.input_order_singleitem_priceExVat.setObjectName("input_order_singleitem_priceExVat")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 110, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.input_orderlineitem_itemcount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_orderlineitem_itemcount.setGeometry(QtCore.QRect(600, 134, 171, 33))
        self.input_orderlineitem_itemcount.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_orderlineitem_itemcount.setText("")
        self.input_orderlineitem_itemcount.setObjectName("input_orderlineitem_itemcount")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 110, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 182, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.button_orderlineitem_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_orderlineitem_clear.setGeometry(QtCore.QRect(540, 540, 101, 41))
        self.button_orderlineitem_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_orderlineitem_clear.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_orderlineitem_clear.setObjectName("button_orderlineitem_clear")
        self.button_orderlineitem_searchGo = QtWidgets.QPushButton(self.centralwidget)
        self.button_orderlineitem_searchGo.setGeometry(QtCore.QRect(340, 20, 51, 33))
        self.button_orderlineitem_searchGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_orderlineitem_searchGo.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_orderlineitem_searchGo.setObjectName("button_orderlineitem_searchGo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bestellpositionen"))
        self.input_orderlineitem_orderId.setPlaceholderText(_translate("MainWindow", "Bestellnummer .."))
        self.input_orderlineitem_totapriceExVat.setPlaceholderText(_translate("MainWindow", "Preis in € .."))
        self.button_orderlineitem_back.setToolTip(_translate("MainWindow", "Esc"))
        self.button_orderlineitem_back.setText(_translate("MainWindow", "Zur Bestellung"))
        self.button_orderlineitem_back.setShortcut(_translate("MainWindow", "Esc"))
        self.button_orderlineitem_newOrderlineitem.setToolTip(_translate("MainWindow", "Strg + N"))
        self.button_orderlineitem_newOrderlineitem.setText(_translate("MainWindow", "Neue Position"))
        self.button_orderlineitem_newOrderlineitem.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.label.setText(_translate("MainWindow", "Preis Netto"))
        self.label_2.setText(_translate("MainWindow", "Preis Brutto"))
        self.label_4.setText(_translate("MainWindow", "Artikel"))
        self.input_orderlineitem_totapriceIclVat.setPlaceholderText(_translate("MainWindow", "Preis in € .."))
        self.button_orderlineitem_saveLine.setToolTip(_translate("MainWindow", "Strg + Enter"))
        self.button_orderlineitem_saveLine.setText(_translate("MainWindow", "Speichern"))
        self.button_orderlineitem_saveLine.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.button_orderlineitem_deleteLine.setToolTip(_translate("MainWindow", "Strg + Entf"))
        self.button_orderlineitem_deleteLine.setText(_translate("MainWindow", "Löschen"))
        self.button_orderlineitem_deleteLine.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.input_order_singleitem_priceExVat.setPlaceholderText(_translate("MainWindow", "Preis in € .."))
        self.label_3.setText(_translate("MainWindow", "Einzelpreis Netto"))
        self.input_orderlineitem_itemcount.setPlaceholderText(_translate("MainWindow", "Stück .."))
        self.label_5.setText(_translate("MainWindow", "Menge"))
        self.label_6.setText(_translate("MainWindow", "Gesamte Position:"))
        self.button_orderlineitem_clear.setToolTip(_translate("MainWindow", "Strg + Rück (<--)"))
        self.button_orderlineitem_clear.setText(_translate("MainWindow", "leeren"))
        self.button_orderlineitem_clear.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.button_orderlineitem_searchGo.setToolTip(_translate("MainWindow", "Enter"))
        self.button_orderlineitem_searchGo.setText(_translate("MainWindow", "Los"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
