# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './viewports/warehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0910909, y1:0.108, x2:1, y2:1, stop:0 rgba(15, 41, 46, 255), stop:1 rgba(26, 109, 117, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_warehouse_search = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_search.setGeometry(QtCore.QRect(20, 20, 311, 33))
        self.input_warehouse_search.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_search.setObjectName("input_warehouse_search")
        self.listView_warehouse_search = QtWidgets.QListWidget(self.centralwidget)
        self.listView_warehouse_search.setGeometry(QtCore.QRect(20, 70, 371, 461))
        self.listView_warehouse_search.setStyleSheet("font: 57 14pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.listView_warehouse_search.setObjectName("listView_warehouse_search")
        self.input_warehouse_articleId = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_articleId.setGeometry(QtCore.QRect(420, 20, 341, 33))
        self.input_warehouse_articleId.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_articleId.setObjectName("input_warehouse_articleId")
        self.input_warehouse_articleName = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_articleName.setGeometry(QtCore.QRect(420, 60, 341, 33))
        self.input_warehouse_articleName.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_articleName.setObjectName("input_warehouse_articleName")
        self.input_warehouse_count_is = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_count_is.setGeometry(QtCore.QRect(420, 274, 161, 33))
        self.input_warehouse_count_is.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_count_is.setObjectName("input_warehouse_count_is")
        self.input_warehouse_storageId = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_storageId.setGeometry(QtCore.QRect(420, 200, 231, 33))
        self.input_warehouse_storageId.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_storageId.setObjectName("input_warehouse_storageId")
        self.input_warehouse_count_want = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_count_want.setGeometry(QtCore.QRect(600, 274, 161, 33))
        self.input_warehouse_count_want.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_count_want.setObjectName("input_warehouse_count_want")
        self.input_warehouse_price = QtWidgets.QLineEdit(self.centralwidget)
        self.input_warehouse_price.setGeometry(QtCore.QRect(420, 344, 231, 33))
        self.input_warehouse_price.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.input_warehouse_price.setObjectName("input_warehouse_price")
        self.button_warehouse_deleteArticle = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_deleteArticle.setGeometry(QtCore.QRect(420, 540, 201, 41))
        self.button_warehouse_deleteArticle.setStyleSheet("background-color: rgba(255, 150, 170, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_warehouse_deleteArticle.setObjectName("button_warehouse_deleteArticle")
        self.button_warehouse_newArticle = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_newArticle.setGeometry(QtCore.QRect(190, 540, 201, 41))
        self.button_warehouse_newArticle.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_warehouse_newArticle.setObjectName("button_warehouse_newArticle")
        self.button_warehouse_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_back.setGeometry(QtCore.QRect(20, 540, 161, 41))
        self.button_warehouse_back.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_warehouse_back.setObjectName("button_warehouse_back")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 250, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 250, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.comboBox_warehouse_category = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_warehouse_category.setGeometry(QtCore.QRect(420, 130, 301, 31))
        self.comboBox_warehouse_category.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_warehouse_category.setObjectName("comboBox_warehouse_category")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 100, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 320, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(420, 420, 341, 111))
        self.listView.setStyleSheet("font: 57 14pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 396, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Maven Pro")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.button_warehouse_deleteArticle_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_deleteArticle_2.setGeometry(QtCore.QRect(720, 490, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Maven Pro Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.button_warehouse_deleteArticle_2.setFont(font)
        self.button_warehouse_deleteArticle_2.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
"alternate-background-color: rgba(0, 0, 0, 50);")
        self.button_warehouse_deleteArticle_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./gui\\edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_warehouse_deleteArticle_2.setIcon(icon)
        self.button_warehouse_deleteArticle_2.setIconSize(QtCore.QSize(25, 25))
        self.button_warehouse_deleteArticle_2.setObjectName("button_warehouse_deleteArticle_2")
        self.button_warehouse_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_clear.setGeometry(QtCore.QRect(630, 540, 131, 41))
        self.button_warehouse_clear.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_warehouse_clear.setObjectName("button_warehouse_clear")
        self.button_warehouse_searchGo = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_searchGo.setGeometry(QtCore.QRect(340, 20, 51, 33))
        self.button_warehouse_searchGo.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_warehouse_searchGo.setObjectName("button_warehouse_searchGo")
        self.button_warehouse_newCategory = QtWidgets.QPushButton(self.centralwidget)
        self.button_warehouse_newCategory.setGeometry(QtCore.QRect(730, 130, 31, 31))
        self.button_warehouse_newCategory.setToolTip("")
        self.button_warehouse_newCategory.setToolTipDuration(-1)
        self.button_warehouse_newCategory.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"alternate-background-color: rgba(0, 0, 0, 50);\n"
"font: 57 16pt \"Maven Pro Medium\";\n"
"color: rgb(255, 255, 255);")
        self.button_warehouse_newCategory.setObjectName("button_warehouse_newCategory")
        self.input_warehouse_search.raise_()
        self.listView_warehouse_search.raise_()
        self.input_warehouse_articleId.raise_()
        self.input_warehouse_articleName.raise_()
        self.input_warehouse_count_is.raise_()
        self.input_warehouse_storageId.raise_()
        self.input_warehouse_count_want.raise_()
        self.input_warehouse_price.raise_()
        self.button_warehouse_deleteArticle.raise_()
        self.button_warehouse_newArticle.raise_()
        self.button_warehouse_back.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox_warehouse_category.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.listView.raise_()
        self.label_6.raise_()
        self.button_warehouse_clear.raise_()
        self.button_warehouse_searchGo.raise_()
        self.button_warehouse_newCategory.raise_()
        self.button_warehouse_deleteArticle_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Artikel"))
        self.input_warehouse_search.setPlaceholderText(_translate("MainWindow", "Suche .."))
        self.input_warehouse_articleId.setPlaceholderText(_translate("MainWindow", "Artikelnummer .."))
        self.input_warehouse_articleName.setPlaceholderText(_translate("MainWindow", "Bezeichnung .."))
        self.input_warehouse_count_is.setPlaceholderText(_translate("MainWindow", "Anzahl .."))
        self.input_warehouse_storageId.setPlaceholderText(_translate("MainWindow", "Fachnummer .."))
        self.input_warehouse_count_want.setPlaceholderText(_translate("MainWindow", "Anzahl .."))
        self.input_warehouse_price.setPlaceholderText(_translate("MainWindow", "Preis in € .."))
        self.button_warehouse_deleteArticle.setToolTip(_translate("MainWindow", "Strg + Entf"))
        self.button_warehouse_deleteArticle.setText(_translate("MainWindow", "Artikel löschen"))
        self.button_warehouse_deleteArticle.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.button_warehouse_newArticle.setToolTip(_translate("MainWindow", "Strg + Enter"))
        self.button_warehouse_newArticle.setText(_translate("MainWindow", "Neuer Artikel"))
        self.button_warehouse_newArticle.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.button_warehouse_back.setToolTip(_translate("MainWindow", "Esc"))
        self.button_warehouse_back.setText(_translate("MainWindow", "Zurück"))
        self.button_warehouse_back.setShortcut(_translate("MainWindow", "Esc"))
        self.label.setText(_translate("MainWindow", "Bestand"))
        self.label_2.setText(_translate("MainWindow", "Meldebestand"))
        self.label_3.setText(_translate("MainWindow", "Lagerfach"))
        self.label_4.setText(_translate("MainWindow", "Kategorie"))
        self.label_5.setText(_translate("MainWindow", "Nettopreis"))
        self.label_6.setText(_translate("MainWindow", "Konflikte"))
        self.button_warehouse_deleteArticle_2.setToolTip(_translate("MainWindow", "Strg + K"))
        self.button_warehouse_deleteArticle_2.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.button_warehouse_clear.setToolTip(_translate("MainWindow", "Strg + Rück (<--)"))
        self.button_warehouse_clear.setText(_translate("MainWindow", "leeren"))
        self.button_warehouse_clear.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.button_warehouse_searchGo.setToolTip(_translate("MainWindow", "Enter"))
        self.button_warehouse_searchGo.setText(_translate("MainWindow", "Los"))
        self.button_warehouse_newCategory.setText(_translate("MainWindow", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
